platform:
    - x64

environment:
    global:
        CYG_MIRROR: http://cygwin.uib.no
        CYG_CACHE: C:/cygwin/var/cache/setup
    matrix:
        -   CYG_ARCH: x86
            CYG_ROOT: C:/cygwin
            WODI_ARCH: 32
            MINGW_ARCH: i686
            OPAM_URL: https://dl.dropboxusercontent.com/s/eo4igttab8ipyle/opam32.tar.xz
        -   CYG_ARCH: x86_64
            CYG_ROOT: C:/cygwin64
            WODI_ARCH: 64
            MINGW_ARCH: x86_64
            OPAM_URL: https://dl.dropboxusercontent.com/s/b2q2vjau7if1c1b/opam64.tar.xz

init:
    - 'echo System architecture: %PLATFORM%'

install:
    - 'appveyor DownloadFile http://cygwin.com/setup-%CYG_ARCH%.exe -FileName setup.exe'
    - 'setup.exe -qnNdO -R "%CYG_ROOT%" -s "%CYG_MIRROR%" -l "%CYG_CACHE%" -P wget  -P dos2unix -P diffutils -P make -P patch -P mingw64-%MINGW_ARCH%-gcc-core -P mingw64-%MINGW_ARCH%-gcc-g++ -P git -P m4 -P rsync -P unzip -P curl >NUL'
    - '%CYG_ROOT%/bin/bash -lc "cygcheck -dc cygwin"'
    - 'appveyor DownloadFile %OPAM_URL% -FileName opam.tar.xz'


build_script:
    - '%CYG_ROOT%/bin/bash -lc "cd \"$OLDPWD\" && ./appveyor/build.sh"'

artifacts:
  - path: test.log
    name: test-logs
